steps:

- name: 'node'
  entrypoint: 'npm'
  args: ['install', '--no-audit']
  waitFor: ['-']
  id: 'frontend-npm-install'
  dir: 'frontend'

- name: 'node'
  args: ['run', 'build']
  waitFor: ['frontend-npm-install']
  id: 'frontend-npm-build'
  dir: 'frontend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
  dir: 'backend'
  waitFor: ['-']


images: 
- 'gcr.io/$PROJECT_ID/backend'

