steps:

- name: 'node'
  entrypoint: 'npm'
  args: ['install', '--no-audit']
  waitFor: ['-']
  id: 'frontend-npm-install'
  dir: 'frontend'

- name: 'node'
  args: ['run', 'build']
  entrypoint: 'npm'
  waitFor: ['frontend-npm-install']
  id: 'frontend-npm-build'
  dir: 'frontend'

- name: 'busybox'
  args: ['tar', 'cvf', 'frontend-$BRANCH_NAME.tgz', '.']
  dir: 'frontend/build'
  waitFor: ['frontend-npm-build']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME', '.']
  dir: 'backend'
  waitFor: ['-']


images:
- 'gcr.io/$PROJECT_ID/backend'

artifacts:
  objects:
    location: 'gs://artifacts.$PROJECT_ID.appspot.com/frontend/'
    paths: ['frontend/build/frontend-$BRANCH_NAME.tgz']
