steps:

- name: 'node:slim'
  entrypoint: 'npm'
  args: ['ci', '--no-audit']
  waitFor: ['-']
  id: 'frontend-npm-install'
  dir: 'frontend'

- name: 'node:slim'
  args: ['run', 'build']
  entrypoint: 'npm'
  waitFor: ['frontend-npm-install']
  id: 'frontend-npm-build'
  dir: 'frontend'

- name: 'busybox'
  args: ['tar', 'cvf', 'frontend-$BRANCH_NAME.tgz', '.']
  dir: 'frontend/build'
  waitFor: ['frontend-npm-build']

# https://cloud.google.com/cloud-build/docs/speeding-up-builds?hl=ja#using_a_cached_docker_image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/backend || exit 0
  waitFor: ['-']
  id: 'pull-cache'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$BRANCH_NAME',
         '--cache-from', 'gcr.io/$PROJECT_ID/backend:latest',
         '.']
  dir: 'backend'
  waitFor: ['pull-cache']


images:
- 'gcr.io/$PROJECT_ID/backend'

artifacts:
  objects:
    location: 'gs://artifacts.$PROJECT_ID.appspot.com/frontend/'
    paths: ['frontend/build/frontend-$BRANCH_NAME.tgz']
