version: '2.0'
services:
  web:
    build: .
    ports:
      - "8000:8000"
  mysql:
    image: mysql:5.7
    container_name: negainoido-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: negainoido
      MYSQL_USER: negainoido
      MYSQL_PASSWORD: negainoido
      MYSQL_DATABASE: icfpc2019
