# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "${GITHUB_REF}"
      id: extract_branch
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.3
    - name: install isort and black
      run: pip install isort black
    - name: apply isort
      run: |
        find . -name '*.py' | xargs isort
      working-directory: backend
    - name: apply black
      working-directory: backend
      run: black .
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.6
      with:
        # Github Token with commit access
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        # Specify commit message
        commit-message: apply formatter
        email: ${name}@users.noreply.github.com
        name: github action
